import XCTest
@testable import Clipvelope

final class CapturePolicyTests: XCTestCase {
    private func shouldCapture(
        types: [String] = ["public.utf8-plain-text"],
        source: String? = "com.apple.Safari",
        ignored: Set<String> = [],
        skipConcealed: Bool = true
    ) -> Bool {
        CapturePolicy.shouldCapture(types: types,
                                    sourceBundleID: source,
                                    ignoredBundleIDs: ignored,
                                    skipConcealed: skipConcealed)
    }

    func testOrdinaryTextIsCaptured() {
        XCTAssertTrue(shouldCapture())
    }

    // The whole point of the feature: a password manager marks a copied
    // credential concealed, and a clipboard manager must not record it.
    func testConcealedContentIsSkipped() {
        XCTAssertFalse(shouldCapture(types: ["public.utf8-plain-text",
                                             "org.nspasteboard.ConcealedType"]))
    }

    func testTransientAndAutoGeneratedContentIsSkipped() {
        XCTAssertFalse(shouldCapture(types: ["org.nspasteboard.TransientType"]))
        XCTAssertFalse(shouldCapture(types: ["org.nspasteboard.AutoGeneratedType"]))
    }

    func testLegacyOnePasswordMarkerIsSkipped() {
        XCTAssertFalse(shouldCapture(types: ["com.agilebits.onepassword"]))
    }

    func testConcealedContentIsCapturedWhenTheUserTurnsTheRuleOff() {
        XCTAssertTrue(shouldCapture(types: ["org.nspasteboard.ConcealedType"],
                                    skipConcealed: false))
    }

    func testIgnoredAppIsSkipped() {
        XCTAssertFalse(shouldCapture(source: "com.1password.1password",
                                     ignored: ["com.1password.1password"]))
    }

    func testIgnoreListIsSkippedEvenWhenConcealedCheckIsOff() {
        XCTAssertFalse(shouldCapture(source: "com.bitwarden.desktop",
                                     ignored: ["com.bitwarden.desktop"],
                                     skipConcealed: false))
    }

    func testUnrelatedAppInTheIgnoreListDoesNotBlockCapture() {
        XCTAssertTrue(shouldCapture(source: "com.apple.Safari",
                                    ignored: ["com.1password.1password"]))
    }

    func testUnknownSourceIsStillCaptured() {
        XCTAssertTrue(shouldCapture(source: nil, ignored: ["com.1password.1password"]))
    }
}
