import Foundation

// The rules that decide what is captured and what the history holds.
// Kept apart from ClipboardMonitor because these are pure functions that a
// test can call directly, where the monitor needs a real pasteboard.

// MARK: - History Policy

/// The rules for maintaining the history list. Pure, so they can be tested
/// without constructing a store (which would reach for the Keychain).
enum HistoryPolicy {
    /// Re-copying something already in history moves it back to the top rather
    /// than adding a duplicate, and stamps it with the new time: the list is in
    /// recency order, and an entry at the top dated last week would be filed
    /// under "Older" while sitting above things copied a minute ago. Dedup
    /// previously compared only against the newest entry, so copying A, B, A
    /// left three entries.
    static func inserting(_ content: ClipboardContent,
                          into items: [ClipboardItem],
                          maxItems: Int,
                          maxPayloadBytes: Int = .max,
                          id: UUID = UUID(),
                          now: Date = Date(),
                          source: String? = nil) -> [ClipboardItem] {
        var items = items
        if let existing = items.firstIndex(where: { $0.content == content }) {
            var item = items.remove(at: existing)
            item.createdAt = now
            items.insert(item, at: 0)
            return items
        }
        items.insert(ClipboardItem(id: id, createdAt: now, isPinned: false,
                                   content: content, sourceBundleID: source),
                     at: 0)
        return trimmed(items, maxItems: maxItems, maxPayloadBytes: maxPayloadBytes)
    }

    static func inserting(_ text: String,
                          into items: [ClipboardItem],
                          maxItems: Int,
                          maxPayloadBytes: Int = .max,
                          id: UUID = UUID(),
                          now: Date = Date()) -> [ClipboardItem] {
        inserting(.text(text), into: items, maxItems: maxItems,
                  maxPayloadBytes: maxPayloadBytes, id: id, now: now)
    }

    /// Pinned items are exempt from both caps -- pinning is a promise to keep it.
    ///
    /// The byte budget exists because image payloads are unbounded in a way text
    /// never was: a count-based cap alone would happily hold 200 screenshots.
    static func trimmed(_ items: [ClipboardItem],
                        maxItems: Int,
                        maxPayloadBytes: Int = .max) -> [ClipboardItem] {
        var items = items
        var payloadBytes = items.reduce(0) { $0 + $1.payloadByteCount }

        while items.count > maxItems || payloadBytes > maxPayloadBytes {
            guard let index = items.lastIndex(where: { !$0.isPinned }) else { break }
            payloadBytes -= items[index].payloadByteCount
            items.remove(at: index)
        }
        return items
    }

    /// Display order: pinned first, each group keeping its recency order.
    static func displayOrder(_ items: [ClipboardItem]) -> [ClipboardItem] {
        items.filter(\.isPinned) + items.filter { !$0.isPinned }
    }
}

// MARK: - Capture Policy

/// Decides whether a pasteboard change should be recorded. Kept pure -- no
/// NSPasteboard, no app state -- so the rules can be tested directly.
enum CapturePolicy {
    /// Markers from the nspasteboard.org convention that apps set to say
    /// "do not record this". Password managers set ConcealedType when you copy
    /// a credential; without honouring it, a clipboard manager quietly becomes
    /// a plaintext-ish log of every password the user copies.
    static let concealedMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // Older marker still set by some password managers.
        "com.agilebits.onepassword"
    ]

    static func shouldCapture(
        types: [String],
        sourceBundleID: String?,
        ignoredBundleIDs: Set<String>,
        skipConcealed: Bool
    ) -> Bool {
        if skipConcealed, types.contains(where: { concealedMarkers.contains($0) }) {
            return false
        }
        if let sourceBundleID, ignoredBundleIDs.contains(sourceBundleID) {
            return false
        }
        return true
    }
}

// MARK: - Polling Policy

/// How often the pasteboard is polled. macOS has no notification for pasteboard
/// changes, so polling is the only mechanism; what this decides is the rate.
///
/// Two rates, not a ramp. A ramp would be more code and more test surface for
/// nothing the user can perceive: the whole span it would interpolate across is
/// already under the time it takes a person to copy something and reach for the
/// panel.
enum PollingPolicy {
    /// The rate while the user is plainly copying things. This is what the
    /// monitor did at every moment before back-off existed, and nobody has
    /// reported a missed or late capture at it, so it is left alone.
    static let active: TimeInterval = 0.6

    /// The rate at rest. Chosen as the largest delay that is still invisible:
    /// even by keyboard, copying something and then opening the panel takes
    /// longer than this, and the first poll after a change snaps the rate back
    /// to `active`, so a burst of copying is polled quickly from its second
    /// item on. It cuts wakeups from 100 a minute to 24 -- a 76 per cent
    /// reduction over an idle hour, which is the case this exists for.
    static let idle: TimeInterval = 2.5

    /// How long after the last change the poll stays at its quickest. Fifteen
    /// seconds covers a normal copy-paste-copy rhythm without holding the fast
    /// rate open on a Mac whose owner has walked away.
    static let activeWindow: TimeInterval = 15

    /// The polling interval for a pasteboard last changed `sinceLastChange`
    /// seconds ago.
    ///
    /// The boundary falls on the idle side: exactly at `activeWindow` the
    /// window has elapsed. A negative argument -- the wall clock moving
    /// backwards under an NTP correction or a timezone change -- reads as
    /// "changed even more recently than now" and yields the active rate, which
    /// is the safe direction: the worst case is a few seconds of quick polling,
    /// where treating it as idle could delay a capture the user is waiting for.
    /// The result is always one of the two constants, so it can never fall
    /// outside `active...idle`.
    static func interval(sinceLastChange: TimeInterval) -> TimeInterval {
        sinceLastChange < activeWindow ? active : idle
    }
}
