import Foundation

// The rules that decide what is captured and what the history holds.
// Kept apart from ClipboardMonitor because these are pure functions that a
// test can call directly, where the monitor needs a real pasteboard.

// MARK: - History Policy

/// The rules for maintaining the history list. Pure, so they can be tested
/// without constructing a store (which would reach for the Keychain).
enum HistoryPolicy {
    /// Re-copying something already in history moves it back to the top rather
    /// than adding a duplicate, and stamps it with the new time: the list is in
    /// recency order, and an entry at the top dated last week would be filed
    /// under "Older" while sitting above things copied a minute ago. Dedup
    /// previously compared only against the newest entry, so copying A, B, A
    /// left three entries.
    static func inserting(_ content: ClipboardContent,
                          into items: [ClipboardItem],
                          maxItems: Int,
                          maxPayloadBytes: Int = .max,
                          id: UUID = UUID(),
                          now: Date = Date(),
                          source: String? = nil) -> [ClipboardItem] {
        var items = items
        if let existing = items.firstIndex(where: { $0.content == content }) {
            var item = items.remove(at: existing)
            item.createdAt = now
            items.insert(item, at: 0)
            return items
        }
        items.insert(ClipboardItem(id: id, createdAt: now, isPinned: false,
                                   content: content, sourceBundleID: source),
                     at: 0)
        return trimmed(items, maxItems: maxItems, maxPayloadBytes: maxPayloadBytes)
    }

    static func inserting(_ text: String,
                          into items: [ClipboardItem],
                          maxItems: Int,
                          maxPayloadBytes: Int = .max,
                          id: UUID = UUID(),
                          now: Date = Date()) -> [ClipboardItem] {
        inserting(.text(text), into: items, maxItems: maxItems,
                  maxPayloadBytes: maxPayloadBytes, id: id, now: now)
    }

    /// Pinned items are exempt from both caps -- pinning is a promise to keep it.
    ///
    /// The byte budget exists because image payloads are unbounded in a way text
    /// never was: a count-based cap alone would happily hold 200 screenshots.
    static func trimmed(_ items: [ClipboardItem],
                        maxItems: Int,
                        maxPayloadBytes: Int = .max) -> [ClipboardItem] {
        var items = items
        var payloadBytes = items.reduce(0) { $0 + $1.payloadByteCount }

        while items.count > maxItems || payloadBytes > maxPayloadBytes {
            guard let index = items.lastIndex(where: { !$0.isPinned }) else { break }
            payloadBytes -= items[index].payloadByteCount
            items.remove(at: index)
        }
        return items
    }

    /// Display order: pinned first, each group keeping its recency order.
    static func displayOrder(_ items: [ClipboardItem]) -> [ClipboardItem] {
        items.filter(\.isPinned) + items.filter { !$0.isPinned }
    }
}

// MARK: - Capture Policy

/// Decides whether a pasteboard change should be recorded. Kept pure -- no
/// NSPasteboard, no app state -- so the rules can be tested directly.
enum CapturePolicy {
    /// Markers from the nspasteboard.org convention that apps set to say
    /// "do not record this". Password managers set ConcealedType when you copy
    /// a credential; without honouring it, a clipboard manager quietly becomes
    /// a plaintext-ish log of every password the user copies.
    static let concealedMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // Older marker still set by some password managers.
        "com.agilebits.onepassword"
    ]

    static func shouldCapture(
        types: [String],
        sourceBundleID: String?,
        ignoredBundleIDs: Set<String>,
        skipConcealed: Bool
    ) -> Bool {
        if skipConcealed, types.contains(where: { concealedMarkers.contains($0) }) {
            return false
        }
        if let sourceBundleID, ignoredBundleIDs.contains(sourceBundleID) {
            return false
        }
        return true
    }
}
